# Generated by Django 6.0.2 on 2026-05-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='EXP que otorga')),
                ('icono', models.CharField(default='🏆', max_length=10, verbose_name='Icono emoji')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'db_table': 'logros',
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de desbloqueo')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_que_lo_tienen', to='Logros.logro')),
            ],
            options={
                'verbose_name': 'Logro de usuario',
                'verbose_name_plural': 'Logros de usuarios',
                'db_table': 'logros_usuario',
            },
        ),
    ]
