# Generated by Django 6.0.2 on 2026-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutendex_id', models.PositiveIntegerField(verbose_name='ID de Gutendex')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('autor', models.CharField(blank=True, max_length=255, verbose_name='Autor')),
                ('portada_url', models.URLField(blank=True, verbose_name='URL de portada')),
                ('progreso', models.PositiveIntegerField(default=0, verbose_name='Progreso (%)')),
                ('estado', models.CharField(choices=[('Por comenzar', 'Por comenzar'), ('En progreso', 'En progreso'), ('Completado', 'Completado')], default='Por comenzar', max_length=20, verbose_name='Estado')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha en que se agregó')),
            ],
            options={
                'verbose_name': 'Entrada de biblioteca',
                'verbose_name_plural': 'Biblioteca',
                'db_table': 'biblioteca',
                'ordering': ['-fecha_agregado'],
            },
        ),
    ]
