# Generated by Django 6.0.2 on 2026-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_gastada', models.PositiveIntegerField(verbose_name='EXP gastada')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del canje')),
            ],
            options={
                'verbose_name': 'Canje',
                'verbose_name_plural': 'Canjes',
                'db_table': 'canjes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del libro')),
                ('autor', models.CharField(blank=True, max_length=200, verbose_name='Autor')),
                ('coste_exp', models.PositiveIntegerField(verbose_name='Coste en EXP')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('portada_url', models.URLField(blank=True, verbose_name='URL de portada')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Disponible?')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'db_table': 'premios',
                'ordering': ['coste_exp'],
            },
        ),
    ]
