# Generated by Django 6.0.2 on 2026-05-18 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Premios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canje',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canje',
            name='premio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='Premios.premio'),
        ),
    ]
